version: '3.8'

services:
  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: warlocks_tech
    ports:
      - '5432:5432'
  backend:
    build: ./backend
    depends_on:
      - database
    environment:
      DATABASE_URL: 'postgresql://admin:admin@database:5432/warlocks_tech'
    ports:
      - '3000:3000'

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - '3001:3001'
